version: '3'

networks: 
  laravel:

services:
  nginx:
    container_name: nginx
    build: 
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: always
    ports: 
      - "8080:80"
    volumes: 
      - ./api:/srv/www/app
    working_dir: /srv/www/app
    depends_on: 
      - php
      - mysql
    networks:
      - laravel

  mysql: 
    container_name : mysql
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: flower
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      # - ./dockerfiles/mysql:/docker-entrypoint-initdb.d
      - ./dockerfiles/mysql:/var/lib/mysql
    networks:
      - laravel

  php:
    container_name : php
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./api:/srv/www/app
    networks:
      - laravel

  frontend_admin:
    image: node:18.17.1-alpine
    container_name: web
    entrypoint: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./web
        target: /srv/app
    tty: true